### ISSUE TITLE
Mock Trading Issue

### ISSUE THREAD

**Issue by BeefBoss01** [Jdools05/mock-trading#1]
WAAAAZUUUUUUUUUUUUUPPP  J-Man the man!?
![image](https://user-images.githubusercontent.com/114112990/228659343-d5a24328-5266-4ac1-8232-e743b215e643.png)

I have an issue. When I'm in my inventory, the current value and the Net Gain/Loss sections all display zeros unless I click on each of my stocks. I honestly can't remember if that's how it has always been but it just feels a little sus. Anyways my brother-man, look into it when you can. I've gotta get morbin though, see ya.

**Comment by Jdools05** [comment]
Hello! 

Thanks for reaching out! The values in the inventory won't populate until you click on them by design. Finnhub, the api to get financial data, limits the amount of calls I can make per second and per minute. I designed the inventory to be clicked as to not overload the limits. This is because if a handful of people all log in at the same time and all those requests run, there is a chance it would overload the limits, temporarily disabling the service. There are ways I could program around this, but I have been very busy with other things and it's not on my priority list. So, for the time being, you will have to click to update your stocks.

If there is anything else that needs my attention, please create another issue.

Thank you and congratulations for being the first one to report anything! ;)

**Comment by BeefBoss01** [comment]
Good morning!

Thank you my good man for getting back to me so soon. I completely understand the way you explained the problem, I could see the program crashing easily when 20 or more peers log on at the same time during a class session. I will accept the responsibility of manually updating the price status if it means saving the universe.

![image](https://user-images.githubusercontent.com/114112990/228901307-d273367c-f875-4d3e-af9b-9a1939243f97.png)

I strive to be the best reporter I can.
Thank you Mr. President
